- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  vars_files:
  - "vars/main.yml"

  tasks:
    - include: tasks/upgrade-system.yml
    - include: tasks/goss.yml
    - include: tasks/add-users.yml
    - include: tasks/docker-engine.yml
    - include: tasks/k8s-dind.yml
    - include: tasks/git.yml
    - include : midnight-commander.yml
