- name: Add sandbox user
  shell: |
    echo TODO
    
- name: Creates directory
  file:
    path: /home/sandbox/.ssh
    state: directory
  become: yes
  become_user: sandbox
  register: result
  
- copy:
    src: "{{ playbook_dir }}/files/home/sandbox/.ssh/authorized_keys"
    dest: "/home/sandbox/.ssh/authorized_keys"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
    when: result
