- name: Install kubeadm-dind-cluster
  shell: |
    wget https://github.com/kubernetes-sigs/kubeadm-dind-cluster/releases/download/v0.1.0/dind-cluster-v1.13.sh
    
    chmod +x dind-cluster-v1.13.sh
    ./dind-cluster-v1.13.sh up
  become: yes
  become_user: sandbox
  
- name: Move kubectl
  shell: |
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    mv ./kubectl /usr/local/bin/kubectl

